# theme: jekyll-theme-cayman

lsi: false
safe: true
source: sandywalls.github.io
theme: jekyll-theme-slate
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
